#Your info
title: Your awesome title
author:
  name: Your Name
  email: your-email@example.com
description: > # ignore newlines until "baseurl:"
  Write a description for your site here. You can edit 
  this line in config.yml. It will appear in your document
  head meta (for Google search results) and in your 
  feed.xml site description.
baseurl: "" # subpath of your site, e.g. /blog
url: "" # base hostname & protocal for your site, e.g. http://example.com

show_exerpts: false # set to true to show excerpts on the homepage
collections:
    - widgets
#Personal Theme Formatting
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
jenstep_theme:
  date_format: "%b %-d, %Y"
  # social links in footer
  social_links:
    github_username: jekyll
    linkedin_username: user-jekyll
    # twitter: jekyllrb
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

# Build settings
theme: jenstep_theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

